framework:
    default_locale: '%app.locale%'
    secret: '%env(APP_SECRET)%'
    enabled_locales: ['fr', 'en']
    session: true
    esi: true
    fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
