hwi_oauth:
    firewall_names: [main]

    resource_owners:
        facebook:
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            scope:               "email public_profile"

        github:
            type:                github
            client_id:           '%env(GITHUB_CLIENT_ID)%'
            client_secret:       '%env(GITHUB_CLIENT_SECRET)%'
            scope:               "user:email"
