homepage:
    path: /{_locale}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: default/homepage.html.twig
        _locale: '%app.locale%'


controllers:
    resource:
        path: '../src/Controller/'
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}
    defaults:
        _locale: '%app.locale%'

hwi_oauth_redirect:
    path: /login/check-google
    controller: HWI\Bundle\OAuthBundle\Controller\ConnectController::connectAction

hwi_oauth_login:
    path: /login
    controller: HWI\Bundle\OAuthBundle\Controller\ConnectController::connectAction


app_logout:
    path: /logout
