parameters:
    app.locale: '%env(APP_LOCALE)%'
    app.notifications.email_sender: anonymous@example.com

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            array $enabledLocales: '%kernel.enabled_locales%'
            string $defaultLocale: '%app.locale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Security\OAuthUserProvider:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\WeatherService:
        arguments:
            $apiKey: '%env(WEATHER_API_KEY)%'
            $city: '%env(WEATHER_CITY)%'
